spring:
  freemarker:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=flase
    data-username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
#       type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters:
      commons-log.connection-logger-name: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true


  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /static/**

server:
  port: 9091
  tomcat:
    uri-encoding: UTF-8


servlet:
  multipart:
    max-file-size:-1
    max-request-size:-1

#mybatis:
#  mapper-locations: classpath:org/quartz/quartz/mapper/*mapper.xml
#  type-aliases-package: org.quartz.test.entity




